-- Seed: Great Loop reusable template v2 from provided CSVs
-- Generated by Codex on 2026-02-20
SET @schema_name := DATABASE();
START TRANSACTION;

-- Stage route definition
DROP TEMPORARY TABLE IF EXISTS tmp_gl_route_v2;
CREATE TEMPORARY TABLE tmp_gl_route_v2 (
  short_code VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  code VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  description VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;
INSERT INTO tmp_gl_route_v2 (short_code, code, name, description, is_default, is_active) VALUES
('GL_REUSE_V2', 'GREAT_LOOP_REUSABLE_V2', 'Great Loop (Reusable Template v2)', 'Clockwise Great Loop template (Chicago -> Inland Rivers -> Gulf -> FL -> Atlantic ICW -> Chesapeake -> Hudson -> Erie -> Great Lakes -> Chicago). Distances are approximate planning values.', 1, 1);

-- Stage ports
DROP TEMPORARY TABLE IF EXISTS tmp_gl_ports_v2;
CREATE TEMPORARY TABLE tmp_gl_ports_v2 (
  name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  state VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  lat DECIMAL(10,7) NULL,
  lng DECIMAL(10,7) NULL,
  region VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  is_major_port TINYINT(1) NULL,
  is_hidden_gem TINYINT(1) NULL
) ENGINE=InnoDB;
INSERT INTO tmp_gl_ports_v2 (name, state, lat, lng, region, is_major_port, is_hidden_gem) VALUES
('Chicago', 'IL', 41.837045, -87.684939, NULL, NULL, NULL),
('Joliet', 'IL', 41.516866, -88.147963, NULL, NULL, NULL),
('Ottawa', 'IL', 41.354046, -88.823408, NULL, NULL, NULL),
('Peoria', 'IL', 40.673377, -89.541764, NULL, NULL, NULL),
('Grafton', 'IL', 38.976454, -90.425698, NULL, NULL, NULL),
('Alton', 'IL', 38.903898, -90.151204, NULL, NULL, NULL),
('Kimmswick', 'MO', 38.365752, -90.364327, NULL, NULL, NULL),
('Cairo', 'IL', 37.006288, -89.18288, NULL, NULL, NULL),
('Paducah', 'KY', 37.070892, -88.644477, NULL, NULL, NULL),
('Grand Rivers', 'KY', 37.004736, -88.23184, NULL, NULL, NULL),
('Counce', 'TN', 35.040447, -88.2717, NULL, NULL, NULL),
('Columbus', 'MS', 33.508208, -88.407128, NULL, NULL, NULL),
('Demopolis', 'AL', 32.499744, -87.826678, NULL, NULL, NULL),
('Mobile', 'AL', 30.668246, -88.107853, NULL, NULL, NULL),
('Pensacola', 'FL', 30.440989, -87.191242, NULL, NULL, NULL),
('Panama City', 'FL', 30.166271, -85.670191, NULL, NULL, NULL),
('Carrabelle', 'FL', 29.854391, -84.66792, NULL, NULL, NULL),
('Tarpon Springs', 'FL', 28.149054, -82.779371, NULL, NULL, NULL),
('Clearwater', 'FL', 27.979419, -82.771256, NULL, NULL, NULL),
('Sarasota', 'FL', 27.294739, -82.433175, NULL, NULL, NULL),
('Fort Myers', 'FL', 26.61982, -81.831673, NULL, NULL, NULL),
('Marco Island', 'FL', 25.932025, -81.704838, NULL, NULL, NULL),
('Clewiston', 'FL', 26.752811, -80.939194, NULL, NULL, NULL),
('Stuart', 'FL', 27.195272, -80.244114, NULL, NULL, NULL),
('Fort Lauderdale', 'FL', 26.141227, -80.146731, NULL, NULL, NULL),
('West Palm Beach', 'FL', 26.745114, -80.127038, NULL, NULL, NULL),
('St. Augustine', 'FL', 29.896152, -81.311128, NULL, NULL, NULL),
('Jacksonville', 'FL', 30.336864, -81.661603, NULL, NULL, NULL),
('Savannah', 'GA', 32.018043, -81.196492, NULL, NULL, NULL),
('Beaufort', 'SC', 32.458085, -80.722543, NULL, NULL, NULL),
('Charleston', 'SC', 32.828017, -79.972896, NULL, NULL, NULL),
('Myrtle Beach', 'SC', 33.71039, -78.886024, NULL, NULL, NULL),
('Wrightsville Beach', 'NC', 34.212991, -77.797924, NULL, NULL, NULL),
('Morehead City', 'NC', 34.727891, -76.739088, NULL, NULL, NULL),
('New Bern', 'NC', 35.096688, -77.072641, NULL, NULL, NULL),
('Elizabeth City', 'NC', 36.294216, -76.238162, NULL, NULL, NULL),
('Norfolk', 'VA', 36.923015, -76.244641, NULL, NULL, NULL),
('Solomons', 'MD', 38.339089, -76.461901, NULL, NULL, NULL),
('Annapolis', 'MD', 38.972152, -76.505332, NULL, NULL, NULL),
('Chesapeake City', 'MD', 39.527212, -75.811653, NULL, NULL, NULL),
('Cape May', 'NJ', 38.941147, -74.898372, NULL, NULL, NULL),
('Atlantic City', 'NJ', 39.377337, -74.45107, NULL, NULL, NULL),
('Highlands', 'NJ', 39.442693, -74.470231, NULL, NULL, NULL),
('New York', 'NY', 40.662712, -73.938677, NULL, NULL, NULL),
('Kingston', 'NY', 41.950861, -73.974596, NULL, NULL, NULL),
('Albany', 'NY', 42.665745, -73.798353, NULL, NULL, NULL),
('Waterford', 'NY', 42.792068, -73.678827, NULL, NULL, NULL),
('Syracuse', 'NY', 43.063823, -76.069789, NULL, NULL, NULL),
('Buffalo', 'NY', 42.892492, -78.859686, NULL, NULL, NULL),
('Erie', 'PA', 42.116594, -80.073503, NULL, NULL, NULL),
('Cleveland', 'OH', 41.478462, -81.679435, NULL, NULL, NULL),
('Detroit', 'MI', 42.383037, -83.102237, NULL, NULL, NULL),
('Mackinac Island', 'MI', 45.860184, -84.625834, NULL, NULL, NULL),
('Charlevoix', 'MI', 45.313795, -85.255632, NULL, NULL, NULL),
('Sturgeon Bay', 'WI', 44.822676, -87.369806, NULL, NULL, NULL),
('Milwaukee', 'WI', 43.063348, -87.966695, NULL, NULL, NULL);

-- Stage segments
DROP TEMPORARY TABLE IF EXISTS tmp_gl_segments_v2;
CREATE TEMPORARY TABLE tmp_gl_segments_v2 (
  order_index INT NOT NULL,
  start_port_name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  start_state VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  end_port_name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  end_state VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  dist_nm DECIMAL(8,2) NOT NULL,
  lock_count INT NOT NULL DEFAULT 0,
  is_offshore TINYINT(1) NOT NULL DEFAULT 0,
  is_icw TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  region VARCHAR(80) NULL
) ENGINE=InnoDB;
INSERT INTO tmp_gl_segments_v2 (order_index, start_port_name, start_state, end_port_name, end_state, dist_nm, lock_count, is_offshore, is_icw, notes, region) VALUES
(1, 'Chicago', 'IL', 'Joliet', 'IL', 35.4, 0, 0, 0, NULL, 'Illinois Waterway'),
(2, 'Joliet', 'IL', 'Ottawa', 'IL', 39.9, 0, 0, 0, NULL, 'Illinois Waterway'),
(3, 'Ottawa', 'IL', 'Peoria', 'IL', 65.3, 0, 0, 0, NULL, 'Illinois Waterway'),
(4, 'Peoria', 'IL', 'Grafton', 'IL', 137.2, 0, 0, 0, NULL, 'Illinois Waterway'),
(5, 'Grafton', 'IL', 'Alton', 'IL', 16.2, 0, 0, 0, NULL, 'Mississippi River'),
(6, 'Alton', 'IL', 'Kimmswick', 'MO', 40.6, 0, 0, 0, NULL, 'Mississippi River'),
(7, 'Kimmswick', 'MO', 'Cairo', 'IL', 118.9, 0, 0, 0, NULL, 'Mississippi River'),
(8, 'Cairo', 'IL', 'Paducah', 'KY', 30.0, 0, 0, 0, NULL, 'Ohio/Tennessee Rivers & Lakes'),
(9, 'Paducah', 'KY', 'Grand Rivers', 'KY', 23.2, 0, 0, 0, NULL, 'Ohio/Tennessee Rivers & Lakes'),
(10, 'Grand Rivers', 'KY', 'Counce', 'TN', 135.6, 0, 0, 0, NULL, 'Ohio/Tennessee Rivers & Lakes'),
(11, 'Counce', 'TN', 'Columbus', 'MS', 110.7, 0, 0, 0, NULL, 'Tennessee-Tombigbee (Tenn-Tom)'),
(12, 'Columbus', 'MS', 'Demopolis', 'AL', 80.7, 0, 0, 0, NULL, 'Tennessee-Tombigbee (Tenn-Tom)'),
(13, 'Demopolis', 'AL', 'Mobile', 'AL', 133.1, 0, 0, 0, NULL, 'Tennessee-Tombigbee (Tenn-Tom)'),
(14, 'Mobile', 'AL', 'Pensacola', 'FL', 54.2, 0, 0, 0, NULL, 'Gulf Coast (Panhandle)'),
(15, 'Pensacola', 'FL', 'Panama City', 'FL', 88.6, 0, 0, 0, NULL, 'Gulf Coast (Panhandle)'),
(16, 'Panama City', 'FL', 'Carrabelle', 'FL', 60.9, 0, 0, 0, NULL, 'Gulf Coast (Panhandle)'),
(17, 'Carrabelle', 'FL', 'Tarpon Springs', 'FL', 149.7, 0, 1, 0, NULL, 'Florida Big Bend Crossing'),
(18, 'Tarpon Springs', 'FL', 'Clearwater', 'FL', 11.2, 0, 0, 0, NULL, 'Florida West Coast'),
(19, 'Clearwater', 'FL', 'Sarasota', 'FL', 49.4, 0, 0, 0, NULL, 'Florida West Coast'),
(20, 'Sarasota', 'FL', 'Fort Myers', 'FL', 56.9, 0, 0, 0, NULL, 'Florida West Coast'),
(21, 'Fort Myers', 'FL', 'Marco Island', 'FL', 46.0, 0, 0, 0, NULL, 'Florida West Coast'),
(22, 'Marco Island', 'FL', 'Clewiston', 'FL', 73.9, 0, 0, 0, NULL, 'Okeechobee Waterway'),
(23, 'Clewiston', 'FL', 'Stuart', 'FL', 52.6, 0, 0, 0, NULL, 'Okeechobee Waterway'),
(24, 'Stuart', 'FL', 'Fort Lauderdale', 'FL', 69.9, 0, 0, 1, NULL, 'Florida East Coast (ICW/Atlantic)'),
(25, 'Fort Lauderdale', 'FL', 'West Palm Beach', 'FL', 39.9, 0, 0, 1, NULL, 'Florida East Coast (ICW/Atlantic)'),
(26, 'West Palm Beach', 'FL', 'St. Augustine', 'FL', 229.2, 0, 0, 1, NULL, 'Florida East Coast (ICW/Atlantic)'),
(27, 'St. Augustine', 'FL', 'Jacksonville', 'FL', 36.9, 0, 0, 1, NULL, 'Florida East Coast (ICW/Atlantic)'),
(28, 'Jacksonville', 'FL', 'Savannah', 'GA', 119.3, 0, 0, 1, NULL, 'Georgia-Carolinas (ICW)'),
(29, 'Savannah', 'GA', 'Beaufort', 'SC', 39.3, 0, 0, 1, NULL, 'Georgia-Carolinas (ICW)'),
(30, 'Beaufort', 'SC', 'Charleston', 'SC', 48.3, 0, 0, 1, NULL, 'Georgia-Carolinas (ICW)'),
(31, 'Charleston', 'SC', 'Myrtle Beach', 'SC', 87.5, 0, 0, 1, NULL, 'Georgia-Carolinas (ICW)'),
(32, 'Myrtle Beach', 'SC', 'Wrightsville Beach', 'NC', 71.3, 0, 0, 1, NULL, 'Georgia-Carolinas (ICW)'),
(33, 'Wrightsville Beach', 'NC', 'Morehead City', 'NC', 66.9, 0, 0, 1, NULL, 'North Carolina (ICW/Sounds)'),
(34, 'Morehead City', 'NC', 'New Bern', 'NC', 30.3, 0, 0, 1, NULL, 'North Carolina (ICW/Sounds)'),
(35, 'New Bern', 'NC', 'Elizabeth City', 'NC', 95.0, 0, 0, 1, NULL, 'North Carolina (ICW/Sounds)'),
(36, 'Elizabeth City', 'NC', 'Norfolk', 'VA', 41.5, 0, 0, 1, NULL, 'North Carolina (ICW/Sounds)'),
(37, 'Norfolk', 'VA', 'Solomons', 'MD', 94.2, 0, 0, 0, NULL, 'Chesapeake Bay'),
(38, 'Solomons', 'MD', 'Annapolis', 'MD', 41.9, 0, 0, 0, NULL, 'Chesapeake Bay'),
(39, 'Annapolis', 'MD', 'Chesapeake City', 'MD', 51.0, 0, 0, 0, NULL, 'Chesapeake Bay'),
(40, 'Chesapeake City', 'MD', 'Cape May', 'NJ', 60.7, 0, 0, 0, NULL, 'Delaware Bay & New Jersey'),
(41, 'Cape May', 'NJ', 'Atlantic City', 'NJ', 36.8, 0, 0, 0, NULL, 'Delaware Bay & New Jersey'),
(42, 'Atlantic City', 'NJ', 'Highlands', 'NJ', 4.4, 0, 0, 0, NULL, 'Delaware Bay & New Jersey'),
(43, 'Highlands', 'NJ', 'New York', 'NY', 84.9, 0, 0, 0, NULL, 'Delaware Bay & New Jersey'),
(44, 'New York', 'NY', 'Kingston', 'NY', 85.1, 0, 0, 0, NULL, 'Hudson River'),
(45, 'Kingston', 'NY', 'Albany', 'NY', 48.0, 0, 0, 0, NULL, 'Hudson River'),
(46, 'Albany', 'NY', 'Waterford', 'NY', 11.1, 0, 0, 0, NULL, 'Erie Canal'),
(47, 'Waterford', 'NY', 'Syracuse', 'NY', 127.6, 0, 0, 0, NULL, 'Erie Canal'),
(48, 'Syracuse', 'NY', 'Buffalo', 'NY', 147.6, 0, 0, 0, NULL, 'Erie Canal'),
(49, 'Buffalo', 'NY', 'Erie', 'PA', 78.2, 0, 0, 0, NULL, 'Great Lakes Return'),
(50, 'Erie', 'PA', 'Cleveland', 'OH', 89.6, 0, 0, 0, NULL, 'Great Lakes Return'),
(51, 'Cleveland', 'OH', 'Detroit', 'MI', 92.0, 0, 0, 0, NULL, 'Great Lakes Return'),
(52, 'Detroit', 'MI', 'Mackinac Island', 'MI', 240.7, 0, 0, 0, NULL, 'Great Lakes Return'),
(53, 'Mackinac Island', 'MI', 'Charlevoix', 'MI', 46.4, 0, 0, 0, NULL, 'Great Lakes Return'),
(54, 'Charlevoix', 'MI', 'Sturgeon Bay', 'WI', 103.8, 0, 0, 0, NULL, 'Great Lakes Return'),
(55, 'Sturgeon Bay', 'WI', 'Milwaukee', 'WI', 119.6, 0, 0, 0, NULL, 'Great Lakes Return'),
(56, 'Milwaukee', 'WI', 'Chicago', 'IL', 82.1, 0, 0, 0, NULL, 'Great Lakes Return');

-- Upsert route template row
INSERT INTO loop_routes (code, name, short_code, description, is_active, version, is_default)
SELECT r.code, r.name, r.short_code, r.description, r.is_active, 1, r.is_default
FROM tmp_gl_route_v2 r
LEFT JOIN loop_routes lr ON lr.short_code = r.short_code
WHERE lr.id IS NULL;

UPDATE loop_routes lr
INNER JOIN tmp_gl_route_v2 r ON lr.short_code = r.short_code
SET lr.code = r.code,
    lr.name = r.name,
    lr.description = r.description,
    lr.is_active = r.is_active,
    lr.is_default = r.is_default,
    lr.updated_at = NOW();

SET @route_id := (SELECT id FROM loop_routes WHERE short_code = (SELECT short_code FROM tmp_gl_route_v2 LIMIT 1) LIMIT 1);

-- Insert missing ports by exact (name,state); update blanks when data is provided
INSERT INTO ports (name, state, lat, lng, region, is_major_port, is_hidden_gem)
SELECT p.name, p.state, p.lat, p.lng, p.region, COALESCE(p.is_major_port,0), COALESCE(p.is_hidden_gem,0)
FROM tmp_gl_ports_v2 p
LEFT JOIN ports t
  ON LOWER(TRIM(t.name)) = LOWER(TRIM(p.name))
 AND LOWER(TRIM(COALESCE(t.state,''))) = LOWER(TRIM(COALESCE(p.state,'')))
WHERE t.id IS NULL;

UPDATE ports t
INNER JOIN tmp_gl_ports_v2 p
  ON LOWER(TRIM(t.name)) = LOWER(TRIM(p.name))
 AND LOWER(TRIM(COALESCE(t.state,''))) = LOWER(TRIM(COALESCE(p.state,'')))
SET t.lat = COALESCE(t.lat, p.lat),
    t.lng = COALESCE(t.lng, p.lng),
    t.region = CASE WHEN (t.region IS NULL OR TRIM(t.region)='') AND p.region IS NOT NULL AND TRIM(p.region)<>'' THEN p.region ELSE t.region END,
    t.is_major_port = COALESCE(t.is_major_port, COALESCE(p.is_major_port,0)),
    t.is_hidden_gem = COALESCE(t.is_hidden_gem, COALESCE(p.is_hidden_gem,0));

-- Resolve port ids for each staged segment
DROP TEMPORARY TABLE IF EXISTS tmp_gl_segments_resolved_v2;
CREATE TEMPORARY TABLE tmp_gl_segments_resolved_v2 AS
SELECT
  s.order_index,
  p1.id AS start_port_id,
  p2.id AS end_port_id,
  s.start_port_name,
  s.end_port_name,
  s.dist_nm,
  s.lock_count,
  s.region,
  s.is_offshore,
  s.is_icw,
  s.notes
FROM tmp_gl_segments_v2 s
INNER JOIN ports p1
  ON LOWER(TRIM(p1.name)) = LOWER(TRIM(s.start_port_name))
 AND LOWER(TRIM(COALESCE(p1.state,''))) = LOWER(TRIM(COALESCE(s.start_state,'')))
INNER JOIN ports p2
  ON LOWER(TRIM(p2.name)) = LOWER(TRIM(s.end_port_name))
 AND LOWER(TRIM(COALESCE(p2.state,''))) = LOWER(TRIM(COALESCE(s.end_state,'')));

-- Insert any segment_library rows that do not already exist by full signature
INSERT INTO segment_library (start_port_name, end_port_name, dist_nm, lock_count, region, is_offshore, is_icw, notes, created_at, updated_at, start_port_id, end_port_id)
SELECT
  s.start_port_name, s.end_port_name, s.dist_nm, s.lock_count, s.region, s.is_offshore, s.is_icw, s.notes, NOW(), NOW(), s.start_port_id, s.end_port_id
FROM tmp_gl_segments_resolved_v2 s
LEFT JOIN segment_library sl
  ON sl.start_port_id = s.start_port_id
 AND sl.end_port_id = s.end_port_id
 AND COALESCE(sl.dist_nm,0) = COALESCE(s.dist_nm,0)
 AND COALESCE(sl.lock_count,0) = COALESCE(s.lock_count,0)
 AND COALESCE(sl.is_offshore,0) = COALESCE(s.is_offshore,0)
 AND COALESCE(sl.is_icw,0) = COALESCE(s.is_icw,0)
 AND COALESCE(TRIM(sl.region),'') = COALESCE(TRIM(s.region),'')
 AND COALESCE(TRIM(sl.notes),'') = COALESCE(TRIM(s.notes),'')
WHERE sl.id IS NULL;

-- Build final mapping for template using best matching segment ids
DROP TEMPORARY TABLE IF EXISTS tmp_gl_template_map_v2;
CREATE TEMPORARY TABLE tmp_gl_template_map_v2 AS
SELECT
  s.order_index,
  MIN(sl.id) AS segment_id
FROM tmp_gl_segments_resolved_v2 s
INNER JOIN segment_library sl
  ON sl.start_port_id = s.start_port_id
 AND sl.end_port_id = s.end_port_id
 AND COALESCE(sl.dist_nm,0) = COALESCE(s.dist_nm,0)
 AND COALESCE(sl.lock_count,0) = COALESCE(s.lock_count,0)
 AND COALESCE(sl.is_offshore,0) = COALESCE(s.is_offshore,0)
 AND COALESCE(sl.is_icw,0) = COALESCE(s.is_icw,0)
 AND COALESCE(TRIM(sl.region),'') = COALESCE(TRIM(s.region),'')
 AND COALESCE(TRIM(sl.notes),'') = COALESCE(TRIM(s.notes),'')
GROUP BY s.order_index;

-- Replace template leg mapping for this route
DELETE FROM route_template_segments WHERE route_id = @route_id;
INSERT INTO route_template_segments (route_id, segment_id, order_index, is_optional, created_at, updated_at)
SELECT @route_id, m.segment_id, m.order_index, 0, NOW(), NOW()
FROM tmp_gl_template_map_v2 m
ORDER BY m.order_index;

-- Clear detours for this template (none provided in this import set)
DELETE dts
FROM route_template_detour_segments dts
INNER JOIN route_template_detours d ON d.id = dts.detour_id
WHERE d.route_id = @route_id;
DELETE FROM route_template_detours WHERE route_id = @route_id;

-- Recompute route totals from mapped segments
UPDATE loop_routes r
SET r.total_nm = (
      SELECT ROUND(COALESCE(SUM(COALESCE(sl.dist_nm,0)),0),2)
      FROM route_template_segments rts
      INNER JOIN segment_library sl ON sl.id = rts.segment_id
      WHERE rts.route_id = @route_id),
    r.total_locks = (
      SELECT COALESCE(SUM(COALESCE(sl.lock_count,0)),0)
      FROM route_template_segments rts
      INNER JOIN segment_library sl ON sl.id = rts.segment_id
      WHERE rts.route_id = @route_id),
    r.updated_at = NOW()
WHERE r.id = @route_id;

-- Safety assertions
SET @seg_count := (SELECT COUNT(*) FROM tmp_gl_segments_v2);
SET @map_count := (SELECT COUNT(*) FROM route_template_segments WHERE route_id = @route_id);
SELECT @route_id AS route_id, @seg_count AS staged_segments, @map_count AS mapped_segments;

COMMIT;
