-- Seed: Import optional detours for GL_REUSE_V2 from CSV v2
-- Generated by Codex on 2026-02-20
START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_gl_detours_v2;
CREATE TEMPORARY TABLE tmp_gl_detours_v2 (
  route_code VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  detour_code VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  description VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  detour_type VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  order_index INT NOT NULL,
  start_port_name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  start_state VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  end_port_name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  end_state VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  dist_nm DECIMAL(8,2) NOT NULL,
  is_offshore TINYINT(1) NOT NULL DEFAULT 0,
  is_icw TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  region VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL
) ENGINE=InnoDB;

INSERT INTO tmp_gl_detours_v2 (
  route_code, detour_code, name, description, detour_type, is_active, sort_order, order_index,
  start_port_name, start_state, end_port_name, end_state, dist_nm, is_offshore, is_icw, notes, region
)
VALUES
  ('GL_REUSE_V2', 'GLD_CHAMPLAIN_STLAW', 'Champlain Canal + St. Lawrence (skip Erie Canal)', 'Alternative to the Erie Canal: Waterford -> Whitehall -> Montreal -> Kingston (ON) -> Oswego -> back to Erie near Syracuse.', 'LOOP', 1, 2, 1, 'Waterford', 'NY', 'Whitehall', 'NY', 65.0, 0, 0, NULL, 'Champlain Canal'),
  ('GL_REUSE_V2', 'GLD_CHAMPLAIN_STLAW', 'Champlain Canal + St. Lawrence (skip Erie Canal)', 'Alternative to the Erie Canal: Waterford -> Whitehall -> Montreal -> Kingston (ON) -> Oswego -> back to Erie near Syracuse.', 'LOOP', 1, 2, 2, 'Whitehall', 'NY', 'Montreal', 'QC', 120.0, 0, 0, NULL, 'Lake Champlain/Richelieu'),
  ('GL_REUSE_V2', 'GLD_CHAMPLAIN_STLAW', 'Champlain Canal + St. Lawrence (skip Erie Canal)', 'Alternative to the Erie Canal: Waterford -> Whitehall -> Montreal -> Kingston (ON) -> Oswego -> back to Erie near Syracuse.', 'LOOP', 1, 2, 3, 'Montreal', 'QC', 'Kingston', 'ON', 145.0, 0, 0, NULL, 'St. Lawrence River'),
  ('GL_REUSE_V2', 'GLD_CHAMPLAIN_STLAW', 'Champlain Canal + St. Lawrence (skip Erie Canal)', 'Alternative to the Erie Canal: Waterford -> Whitehall -> Montreal -> Kingston (ON) -> Oswego -> back to Erie near Syracuse.', 'LOOP', 1, 2, 4, 'Kingston', 'ON', 'Oswego', 'NY', 55.0, 0, 0, NULL, 'Lake Ontario'),
  ('GL_REUSE_V2', 'GLD_CHAMPLAIN_STLAW', 'Champlain Canal + St. Lawrence (skip Erie Canal)', 'Alternative to the Erie Canal: Waterford -> Whitehall -> Montreal -> Kingston (ON) -> Oswego -> back to Erie near Syracuse.', 'LOOP', 1, 2, 5, 'Oswego', 'NY', 'Syracuse', 'NY', 40.0, 0, 0, NULL, 'Oswego Canal'),
  ('GL_REUSE_V2', 'GLD_KEYS_OUTSIDE', 'Florida Keys Outside Route (skip Okeechobee)', 'Alternative to the Okeechobee Waterway: run outside via the Florida Keys and the Atlantic side. Rejoins at Fort Lauderdale.', 'LOOP', 1, 1, 1, 'Marco Island', 'FL', 'Marathon', 'FL', 95.0, 1, 0, NULL, 'Florida Keys (Offshore)'),
  ('GL_REUSE_V2', 'GLD_KEYS_OUTSIDE', 'Florida Keys Outside Route (skip Okeechobee)', 'Alternative to the Okeechobee Waterway: run outside via the Florida Keys and the Atlantic side. Rejoins at Fort Lauderdale.', 'LOOP', 1, 1, 2, 'Marathon', 'FL', 'Key West', 'FL', 48.0, 1, 0, NULL, 'Florida Keys (Offshore)'),
  ('GL_REUSE_V2', 'GLD_KEYS_OUTSIDE', 'Florida Keys Outside Route (skip Okeechobee)', 'Alternative to the Okeechobee Waterway: run outside via the Florida Keys and the Atlantic side. Rejoins at Fort Lauderdale.', 'LOOP', 1, 1, 3, 'Key West', 'FL', 'Fort Lauderdale', 'FL', 150.0, 1, 0, NULL, 'Atlantic Coast (Offshore)');

-- Resolve route id and ensure route exists
SET @route_id := (
  SELECT id FROM loop_routes WHERE short_code = (SELECT route_code FROM tmp_gl_detours_v2 LIMIT 1) LIMIT 1
);

-- Stage endpoint ports once (avoids MySQL temp table reopen issues)
DROP TEMPORARY TABLE IF EXISTS tmp_gl_detour_ports_v2;
CREATE TEMPORARY TABLE tmp_gl_detour_ports_v2 (
  name VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  state VARCHAR(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  UNIQUE KEY uq_tmp_gl_detour_ports_v2 (name, state)
) ENGINE=InnoDB;

INSERT INTO tmp_gl_detour_ports_v2 (name, state)
SELECT DISTINCT start_port_name, start_state
FROM tmp_gl_detours_v2;

INSERT IGNORE INTO tmp_gl_detour_ports_v2 (name, state)
SELECT DISTINCT end_port_name, end_state
FROM tmp_gl_detours_v2;

-- Upsert any missing endpoint ports by exact (name,state)
INSERT INTO ports (name, state, lat, lng, region, is_major_port, is_hidden_gem)
SELECT p.name, p.state, NULL AS lat, NULL AS lng, NULL AS region, 0, 0
FROM tmp_gl_detour_ports_v2 p
LEFT JOIN ports t
  ON LOWER(TRIM(t.name)) = LOWER(TRIM(p.name))
 AND LOWER(TRIM(COALESCE(t.state,''))) = LOWER(TRIM(COALESCE(p.state,'')))
WHERE t.id IS NULL;

-- Resolve rows to route and port ids
DROP TEMPORARY TABLE IF EXISTS tmp_gl_detours_resolved_v2;
CREATE TEMPORARY TABLE tmp_gl_detours_resolved_v2 AS
SELECT
  lr.id AS route_id,
  d.detour_code, d.name, d.description, d.detour_type, d.is_active, d.sort_order, d.order_index,
  p1.id AS start_port_id, p2.id AS end_port_id,
  d.start_port_name, d.end_port_name, d.dist_nm, 0 AS lock_count, d.is_offshore, d.is_icw, d.notes, d.region
FROM tmp_gl_detours_v2 d
INNER JOIN loop_routes lr ON lr.short_code = d.route_code
INNER JOIN ports p1
  ON LOWER(TRIM(p1.name)) = LOWER(TRIM(d.start_port_name))
 AND LOWER(TRIM(COALESCE(p1.state,''))) = LOWER(TRIM(COALESCE(d.start_state,'')))
INNER JOIN ports p2
  ON LOWER(TRIM(p2.name)) = LOWER(TRIM(d.end_port_name))
 AND LOWER(TRIM(COALESCE(p2.state,''))) = LOWER(TRIM(COALESCE(d.end_state,'')));

-- Insert missing segment_library rows for detour legs
INSERT INTO segment_library (
  start_port_name, end_port_name, dist_nm, lock_count, region, is_offshore, is_icw, notes, created_at, updated_at, start_port_id, end_port_id
)
SELECT
  r.start_port_name, r.end_port_name, r.dist_nm, r.lock_count, r.region, r.is_offshore, r.is_icw, r.notes, NOW(), NOW(), r.start_port_id, r.end_port_id
FROM tmp_gl_detours_resolved_v2 r
LEFT JOIN segment_library sl
  ON sl.start_port_id = r.start_port_id
 AND sl.end_port_id = r.end_port_id
 AND COALESCE(sl.dist_nm,0) = COALESCE(r.dist_nm,0)
 AND COALESCE(sl.lock_count,0) = COALESCE(r.lock_count,0)
 AND COALESCE(sl.is_offshore,0) = COALESCE(r.is_offshore,0)
 AND COALESCE(sl.is_icw,0) = COALESCE(r.is_icw,0)
 AND COALESCE(TRIM(sl.region),'') = COALESCE(TRIM(r.region),'')
 AND COALESCE(TRIM(sl.notes),'') = COALESCE(TRIM(r.notes),'')
WHERE sl.id IS NULL;

-- Build deterministic segment mapping for each detour leg row
DROP TEMPORARY TABLE IF EXISTS tmp_gl_detour_segment_map_v2;
CREATE TEMPORARY TABLE tmp_gl_detour_segment_map_v2 AS
SELECT
  r.route_id, r.detour_code, r.order_index, MIN(sl.id) AS segment_id
FROM tmp_gl_detours_resolved_v2 r
INNER JOIN segment_library sl
  ON sl.start_port_id = r.start_port_id
 AND sl.end_port_id = r.end_port_id
 AND COALESCE(sl.dist_nm,0) = COALESCE(r.dist_nm,0)
 AND COALESCE(sl.lock_count,0) = COALESCE(r.lock_count,0)
 AND COALESCE(sl.is_offshore,0) = COALESCE(r.is_offshore,0)
 AND COALESCE(sl.is_icw,0) = COALESCE(r.is_icw,0)
 AND COALESCE(TRIM(sl.region),'') = COALESCE(TRIM(r.region),'')
 AND COALESCE(TRIM(sl.notes),'') = COALESCE(TRIM(r.notes),'')
GROUP BY r.route_id, r.detour_code, r.order_index;

-- Upsert detour headers (one row per route+detour_code)
INSERT INTO route_template_detours (
  route_id, detour_code, name, description, detour_type, is_active, sort_order, insert_after_port_id, insert_after_segment_id
)
SELECT
  h.route_id, h.detour_code, h.name, h.description, h.detour_type, h.is_active, h.sort_order, NULL, NULL
FROM (
  SELECT route_id, detour_code,
         MIN(name) AS name,
         MIN(description) AS description,
         MIN(detour_type) AS detour_type,
         MAX(is_active) AS is_active,
         MIN(sort_order) AS sort_order
  FROM tmp_gl_detours_resolved_v2
  GROUP BY route_id, detour_code
) h
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  detour_type = VALUES(detour_type),
  is_active = VALUES(is_active),
  sort_order = VALUES(sort_order),
  insert_after_port_id = NULL,
  insert_after_segment_id = NULL;

-- Replace segment mapping for detours in this import
DELETE dts
FROM route_template_detour_segments dts
INNER JOIN route_template_detours d ON d.id = dts.detour_id
INNER JOIN (SELECT DISTINCT route_id, detour_code FROM tmp_gl_detours_resolved_v2) i
  ON i.route_id = d.route_id AND i.detour_code = d.detour_code;

INSERT INTO route_template_detour_segments (detour_id, segment_id, order_index)
SELECT
  d.id AS detour_id, m.segment_id, m.order_index
FROM tmp_gl_detour_segment_map_v2 m
INNER JOIN route_template_detours d
  ON d.route_id = m.route_id AND d.detour_code = m.detour_code
ORDER BY d.id, m.order_index;

-- Summary
SELECT
  (SELECT COUNT(*) FROM route_template_detours WHERE route_id = @route_id) AS detour_count,
  (SELECT COUNT(*) FROM route_template_detour_segments dts INNER JOIN route_template_detours d ON d.id=dts.detour_id WHERE d.route_id = @route_id) AS detour_segment_count,
  (SELECT COUNT(*) FROM tmp_gl_detours_resolved_v2) AS staged_rows,
  (SELECT COUNT(*) FROM tmp_gl_detour_segment_map_v2) AS mapped_rows;

COMMIT;
