-- Great Loop bridge reference library foundation.
-- Source: Bridge_Master from great_loop_bridges_final_consolidated_phase_17_21.xlsx.

CREATE TABLE IF NOT EXISTS great_loop_bridges (
  id BIGINT NOT NULL AUTO_INCREMENT,
  bridge_id VARCHAR(40) NULL,
  bridge_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  route_segment VARCHAR(255) NULL,
  route_variant VARCHAR(255) NULL,
  waterway VARCHAR(255) NULL,
  state_province VARCHAR(80) NULL,
  nearest_city VARCHAR(160) NULL,
  mile_marker VARCHAR(80) NULL,
  latitude DECIMAL(12,8) NULL,
  longitude DECIMAL(12,8) NULL,
  bridge_type VARCHAR(120) NULL,
  is_drawbridge TINYINT(1) NOT NULL DEFAULT 0,
  is_fixed TINYINT(1) NOT NULL DEFAULT 0,
  is_railroad TINYINT(1) NOT NULL DEFAULT 0,
  vertical_clearance_closed_ft DECIMAL(8,2) NULL,
  vertical_clearance_open_ft DECIMAL(8,2) NULL,
  horizontal_clearance_ft DECIMAL(8,2) NULL,
  air_draft_notes TEXT NULL,
  opening_schedule TEXT NULL,
  vhf_channel VARCHAR(80) NULL,
  phone VARCHAR(120) NULL,
  operator_contact VARCHAR(255) NULL,
  navigation_notes TEXT NULL,
  short_description TEXT NULL,
  regulatory_notes TEXT NULL,
  source_primary_url TEXT NULL,
  source_secondary_url TEXT NULL,
  image_url TEXT NULL,
  image_source TEXT NULL,
  image_credit TEXT NULL,
  image_license VARCHAR(255) NULL,
  image_allowed_for_fpw TINYINT(1) NOT NULL DEFAULT 0,
  local_image_path VARCHAR(500) NULL,
  source_confidence VARCHAR(120) NULL,
  last_verified_date DATE NULL,
  display_priority INT NOT NULL DEFAULT 100,
  verification_status VARCHAR(120) NULL,
  public_status VARCHAR(80) NOT NULL DEFAULT 'admin_review',
  admin_notes TEXT NULL,
  source_filename VARCHAR(255) NULL,
  source_sheet VARCHAR(128) NULL,
  import_batch_id CHAR(36) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glb_slug (slug),
  UNIQUE KEY uq_glb_bridge_id (bridge_id),
  KEY idx_glb_route_segment (route_segment),
  KEY idx_glb_route_variant (route_variant),
  KEY idx_glb_waterway (waterway),
  KEY idx_glb_state (state_province),
  KEY idx_glb_bridge_type (bridge_type),
  KEY idx_glb_is_drawbridge (is_drawbridge),
  KEY idx_glb_public_status (public_status),
  KEY idx_glb_verification_status (verification_status),
  KEY idx_glb_coordinates (latitude, longitude),
  KEY idx_glb_import_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS great_loop_bridge_import_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  import_filename VARCHAR(255) NULL,
  rows_read INT NOT NULL DEFAULT 0,
  rows_inserted INT NOT NULL DEFAULT 0,
  rows_updated INT NOT NULL DEFAULT 0,
  rows_skipped INT NOT NULL DEFAULT 0,
  rows_errored INT NOT NULL DEFAULT 0,
  do_not_publish_count INT NOT NULL DEFAULT 0,
  planning_only_count INT NOT NULL DEFAULT 0,
  published_count INT NOT NULL DEFAULT 0,
  summary_json LONGTEXT NULL,
  created_by_user_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_glbil_created_at (created_at),
  KEY idx_glbil_created_by (created_by_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
