CREATE TABLE IF NOT EXISTS floatplan_companion_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile_submission_id VARCHAR(128) NOT NULL,
  user_id INT NOT NULL,
  floatplan_id INT NOT NULL,
  route_instance_id INT NULL,
  leg_order INT NULL,
  event_type VARCHAR(32) NOT NULL,
  canonical_status VARCHAR(64) NOT NULL,
  note TEXT NULL,
  checkin_context VARCHAR(32) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  gps_accuracy_meters DECIMAL(10,2) NULL,
  gps_altitude_meters DECIMAL(10,2) NULL,
  speed_knots DECIMAL(8,3) NULL,
  heading_degrees DECIMAL(6,2) NULL,
  location_captured_at_utc DATETIME NULL,
  device_uuid VARCHAR(128) NULL,
  device_platform VARCHAR(32) NULL,
  app_version VARCHAR(40) NULL,
  offline_created_at_utc DATETIME NULL,
  received_at_utc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at_utc DATETIME NULL,
  process_status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
  process_error TEXT NULL,
  created_utc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_utc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_companion_events_user_submission (user_id, mobile_submission_id),
  KEY idx_companion_events_user_received (user_id, received_at_utc),
  KEY idx_companion_events_floatplan_received (floatplan_id, received_at_utc),
  KEY idx_companion_events_route_received (route_instance_id, received_at_utc),
  KEY idx_companion_events_status_received (process_status, received_at_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
