<cfcomponent output="false" hint="Combined account-wide and canonical-trip Premium access authority.">
  <cffunction name="init" access="public" returntype="any" output="false"><cfargument name="datasource" type="string" required="false" default="fpw"><cfscript>variables.datasource=len(trim(arguments.datasource))?trim(arguments.datasource):"fpw";variables.memberService="";variables.tripService="";return this;</cfscript></cffunction>

  <cffunction name="getEffectiveAccess" access="public" returntype="struct" output="false"><cfargument name="userId" type="numeric" required="true"><cfargument name="canonicalTripId" type="numeric" required="false" default="0"><cfscript>
    var uid=int(val(arguments.userId));var tripId=int(val(arguments.canonicalTripId));var account=getMemberService().getCurrentAccess(uid);var counts=getTripService().getTripCounts(uid);var trip={};var accountWide=structKeyExists(account,"hasPremium") AND account.hasPremium;var tripPremium=false;var source=accountWide?(structKeyExists(account,"premiumSource")?account.premiumSource:"account_wide"):"none";var reason=accountWide?"ACCOUNT_WIDE_PREMIUM":"BASIC";var activeTripId=getTripService().getActiveTripId(uid);var legacyPassActive=false;var sourceIndex=0;
    if(structKeyExists(account,"premiumSources") AND isArray(account.premiumSources)){for(sourceIndex=1;sourceIndex<=arrayLen(account.premiumSources);sourceIndex++){if(compareNoCase(account.premiumSources[sourceIndex],"three_day_pass") EQ 0){legacyPassActive=true;break;}}}
    if(tripId GT 0){trip=getTripService().getTripEntitlementForCanonicalTrip(uid,tripId);tripPremium=!structIsEmpty(trip) AND listFindNoCase("RESERVED,ACTIVE",trip.status) GT 0;if(tripPremium AND !accountWide){source="premium_trip";reason="TRIP_ENTITLEMENT_" & trip.status;}}
    return {authenticated=structKeyExists(account,"authenticated")?account.authenticated:(uid GT 0),userId=uid,canonicalTripId=tripId,accountWidePremium=accountWide,tripPremium=tripPremium,hasPremiumForTrip=(accountWide OR tripPremium),availableTripCount=counts.available,reservedTripCount=counts.reserved,activeTripCount=counts.active,activeTripId=activeTripId,currentPlan=accountWide?"premium":(tripPremium?"premium_trip":"basic"),legacyPassActive=legacyPassActive,reason=reason,source=source,accountAccess=account,tripEntitlement=trip};
  </cfscript></cffunction>
  <cffunction name="hasAccountWidePremium" access="public" returntype="boolean" output="false"><cfargument name="userId" type="numeric" required="true"><cfreturn getMemberService().hasPremiumAccess(arguments.userId)></cffunction>
  <cffunction name="hasPremiumForTrip" access="public" returntype="boolean" output="false"><cfargument name="userId" type="numeric" required="true"><cfargument name="canonicalTripId" type="numeric" required="true"><cfreturn getEffectiveAccess(arguments.userId,arguments.canonicalTripId).hasPremiumForTrip></cffunction>
  <cffunction name="hasAvailablePremiumTrip" access="public" returntype="boolean" output="false"><cfargument name="userId" type="numeric" required="true"><cfreturn getTripService().getTripCounts(arguments.userId).available GT 0></cffunction>
  <cffunction name="getMemberService" access="private" returntype="any" output="false"><cfscript>if(!isObject(variables.memberService)){try{variables.memberService=createObject("component","fpw.api.v1.MemberEntitlementService").init(variables.datasource);}catch(any e){variables.memberService=createObject("component","api.v1.MemberEntitlementService").init(variables.datasource);}}return variables.memberService;</cfscript></cffunction>
  <cffunction name="getTripService" access="private" returntype="any" output="false"><cfscript>if(!isObject(variables.tripService)){try{variables.tripService=createObject("component","fpw.api.v1.PremiumTripEntitlementService").init(variables.datasource);}catch(any e){variables.tripService=createObject("component","api.v1.PremiumTripEntitlementService").init(variables.datasource);}}return variables.tripService;</cfscript></cffunction>
</cfcomponent>
