import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import {createRequire} from 'node:module';
import {gzipSync} from 'node:zlib';
const require = createRequire(import.meta.url);
const read = name => readFileSync(new URL('../'+name,import.meta.url),'utf8');
const page = read('boat-loan-calculator/index.cfm');

test('public page scrubs before shared analytics, has no replay and serves canonical metadata',()=>{
  assert.ok(page.indexOf('boat-cost-bootstrap.js') < page.indexOf('template="../includes/analytics_ga4.cfm"'));
  for (const guard of ['fpwPlausibleTagRendered','fpwGa4TagRendered','fpwClarityTagRendered']) assert.match(page,new RegExp('request\\.'+guard+' = true'));
  assert.doesNotMatch(page,/analytics_clarity|trustedsite\.cfm|FAQPage/);
  assert.match(page,/Referrer-Policy" value="no-referrer/);
  assert.match(page,/<noscript>/);
  assert.match(page,/data-clarity-mask="true"/);
  const data = JSON.parse(page.match(/<script type="application\/ld\+json">([^]*?)<\/script>/)[1]);
  assert.deepEqual(data['@graph'].map(x=>x['@type']),['WebPage','BreadcrumbList']);
});

test('bootstrap retains the fragment only in memory, removes all URL state and fails closed',()=>{
  function run(fail){
    const location={hash:'#bc=financial-sentinel',search:'?amount=private-sentinel',pathname:'/boat-loan-calculator/'};
    const window={location,history:{replaceState(a,b,p){assert.equal(p,location.pathname);if(fail)throw Error();location.hash='';location.search='';}}};
    vm.runInNewContext(read('assets/js/boat-cost-bootstrap.js'),{window});return window;
  }
  const good=run(false);assert.equal(good.FPWBoatCostBootstrap.fragment,'#bc=financial-sentinel');assert.equal(good.FPWBoatCostBootstrap.clean,true);assert.equal(good.location.search,'');
  const bad=run(true);assert.equal(bad.FPWBoatCostBootstrap.clean,false);
  let calls=0;bad.FPWBoatCostAnalyticsReady=true;bad.FPWBoatCostState={sanitizeEvent(){calls++;}};bad.FPWAnalytics.track('boat_cost_start',{});assert.equal(calls,0);
});

test('privacy transport strips unexpected fields and respects browser tracking denial',()=>{
  const state=require('../assets/js/boat-cost-state.js');
  function run(denied=false){
    const scripts=[];const calls=[];
    const window={FPWBoatCostBootstrap:{clean:true},FPWBoatCostState:state,navigator:{doNotTrack:denied?'1':'0'},localStorage:{getItem(){return null;}}};
    const document={createElement(){return {};},head:{appendChild(s){scripts.push(s);}}};
    vm.runInNewContext(read('assets/js/boat-cost-analytics.js'),{window,document});
    return {window,scripts,calls};
  }
  const {window,scripts}=run();assert.equal(scripts.length,1);assert.equal(scripts[0].referrerPolicy,'no-referrer');
  const config=window.plausible.o;
  for (const key of ['autoCapturePageviews','outboundLinks','fileDownloads','formSubmissions','hashBasedRouting']) assert.equal(config[key],false);
  const output=config.transformRequest({n:'boat_cost_calculate',u:'https://x/?amount=123#secret',r:'https://x/?identity=private',p:{label:'Secret Name',boat_price:123,direction:'price'},v:36,$:{amount:123},custom:'secret'});
  assert.deepEqual(JSON.parse(JSON.stringify(output)),{n:'boat_cost_calculate',u:'https://floatplanwizard.com/boat-loan-calculator/',d:'floatplanwizard.com',r:null,p:{calculator_version:'1.0',direction:'price'},v:36});
  assert.equal(config.transformRequest({n:'Form: Submission'}),null);
  assert.equal(run(true).scripts.length,0);
});

test('static examples are generated by the shared engine and feature assets meet transfer budget',()=>{
  const {render}=require('../scripts/generate-boat-cost-examples.cjs');
  assert.equal(read('boat-loan-calculator/examples.cfm'),render());
  const files=['assets/js/boat-cost-engine.js','assets/js/boat-cost-state.js','assets/js/boat-cost-ui.js','assets/js/boat-cost-bootstrap.js','assets/js/boat-cost-analytics.js','assets/css/boat-cost.css'];
  const total=files.reduce((sum,file)=>sum+gzipSync(read(file)).length,0);
  assert.ok(total<50*1024,`Feature payload is ${total} bytes gzipped`);
});

test('route and integration links are feature-local',()=>{
  const config=read('web.config');
  assert.match(config,/name="Boat Cost Clean URL to CFM"/);
  assert.match(config,/url="\/boat-loan-calculator\/index.cfm"/);
  assert.equal((read('sitemap.xml').match(/https:\/\/floatplanwizard.com\/boat-loan-calculator\//g)||[]).length,1);
  assert.match(read('boat-fuel-calculator/boat-fuel-calculator.cfm'),/Boat Loan and Ownership Cost Calculator<\/a>/);
  assert.match(read('how-it-works.cfm'),/Boat Loan and Ownership Cost Calculator<\/a>/);
});
