const {test,expect}=require("@playwright/test");
const fs=require("fs");
const path=require("path");
const BASE="http://localhost:8500/fpw";
const output=process.env.FPW_AUTH_ARTIFACT_DIR;
const password="Disposable Auth Live 42!";
test.skip(process.env.FPW_AUTH_LIVE!=="1","Explicit local live-auth opt-in required");
test.setTimeout(180000);
test("live modal signup, explicit readiness continuation, existing login, multi-tab and mobile dashboard",async({browser})=>{
  if(!output) throw new Error("FPW_AUTH_ARTIFACT_DIR required");
  const resume=process.env.FPW_AUTH_RESUME;
  const ledger=resume ? JSON.parse(fs.readFileSync(resume,"utf8")) : {email:"codex-auth-live-"+Date.now()+"@example.test",password,checks:[],userId:0,createdAt:new Date().toISOString()};
  const email=ledger.email;
  const artifact=resume || path.join(output,email.split("@")[0]+".json");
  const record=name=>{ledger.checks.push(name);fs.writeFileSync(artifact,JSON.stringify(ledger,null,2),{mode:0o600});};
  record("fixture selected");
  const context=await browser.newContext({viewport:{width:1440,height:1000},...(resume ? {storageState:artifact.replace(".json","-session.json")} : {})});
  const authEvents=[];
  await context.exposeBinding("recordAuthEvent",(_,name,metadata)=>authEvents.push({name,metadata}));
  await context.addInitScript(()=>{
    document.addEventListener("DOMContentLoaded",()=>{
      if(!window.FPWAnalytics || typeof FPWAnalytics.track!=="function") return;
      const original=FPWAnalytics.track;
      FPWAnalytics.track=function(name,metadata){
        if(String(name).startsWith("auth_")) window.recordAuthEvent(name,metadata);
        return original.apply(this,arguments);
      };
    });
  });
  const page=await context.newPage();
  const pageErrors=[];page.on("pageerror",e=>pageErrors.push(e.message));
  try {
    if (resume) {
      await page.goto(BASE+"/app/login.cfm");
      const login=await page.evaluate(({email,password})=>Api.login(email,password),{email,password});
      expect(login.SUCCESS && login.AUTH).toBe(true);
      await page.goto(BASE+"/app/dashboard.cfm");
      await expect(page.locator("[data-fpw-member-identity]").first()).toHaveText(email);
    } else {
    await page.goto(BASE+"/great-loop/trip-planning/");
    const trigger=page.locator('a[data-fpw-auth-intent="planner"][data-fpw-auth-section="daily_decisions"]');
    await trigger.click();
    await expect(page.locator("#fpwAuthModal")).toBeVisible();
    await expect(page.locator("#fpwAuthEmail")).toBeFocused();
    await page.locator("#fpwAuthPassword").fill("discard me");
    await page.keyboard.press("Escape");
    await expect(page.locator("#fpwAuthModal")).toBeHidden();
    await expect(page.locator("#fpwAuthPassword")).toHaveValue("");
    await expect(trigger).toBeFocused();
    record("native dialog focus, Escape, password clearing, trigger focus restored");
    await trigger.click();
    const beforeCookie=(await context.cookies()).find(c=>["JSESSIONID","CFID"].includes(c.name.toUpperCase()));
    await expect(page.locator("#fpwAuthModal")).toHaveAttribute("data-clarity-mask","True");
    await page.locator("#fpwAuthEmail").fill(email);
    await page.locator("#fpwAuthPassword").fill(password);
    const signupPromise=page.waitForResponse(r=>r.url().includes("auth.cfc?method=handle")&&r.request().method()==="POST"&&r.request().postDataJSON().action==="continue");
    await page.locator("#fpwAuthContinue").click();
    expect((await signupPromise).status()).toBe(200);
    await page.waitForURL(/app\/dashboard\.cfm\?authIntent=/);
    ledger.intentToken=new URL(page.url()).searchParams.get("authIntent");
    await expect(page.locator("#dashboardGettingStartedPanel")).toBeVisible();
    await expect(page.locator("#dashboardAlert")).toContainText("Account created");
    await expect(page.locator("#dashboardAlert")).toContainText(email);
    await expect(page.locator("#routeBuilderModal")).toBeHidden();
    await expect(page.locator("#vesselModal")).toBeHidden();
    await expect(page.locator("#welcomeOnboardingModal")).toBeHidden();
    await expect(page.locator("[data-fpw-member-identity]").first()).toHaveText(email);
    await expect(page.locator("#authContinuationBtn")).toBeDisabled();
    const initial=await page.evaluate(()=>Api.getDashboardOnboardingState());
    const state=initial.ONBOARDING||initial.onboarding;
    expect(state.checklist.allComplete).toBe(false);
    expect(state.checklist.requiredWaypointCount).toBe(2);
    expect(await page.locator("#dashboardGettingStartedPanel").textContent()).not.toMatch(/member name|first name|last name/i);
    const afterCookie=(await context.cookies()).find(c=>["JSESSIONID","CFID"].includes(c.name.toUpperCase()));
    expect(beforeCookie).toBeTruthy();expect(afterCookie).toBeTruthy();
    expect(afterCookie.value).not.toBe(beforeCookie.value);
    expect(afterCookie.httpOnly).toBe(true);
    expect(afterCookie.sameSite).toBe("Lax");
    expect(authEvents.filter(e=>e.name==="auth_continuation_success")).toHaveLength(0);
    record("new unnamed account signs in, lands full overview with four prerequisites and no auto editor");
    record("signup rotates actual HttpOnly SameSite Lax session cookie; overview does not emit planner success");
    await page.locator("#openRouteBuilderBtn").click();
    await expect(page.locator("#routeBuilderModal")).toBeHidden();
    record("planning prerequisites block nameless new account by setup, not member name");
    await page.evaluate(()=>FPW.DashboardModules.onboarding.acknowledgeOverview());
    const results=await page.evaluate(async({email})=>{
      const result=[];
      result.push(await Api.saveVessel({vessel:{VESSELID:0,VESSELNAME:"Auth Live Vessel",REGISTRATION:"",TYPE:"Power",LENGTH:"24",MAX_SPEED:"20",MOST_EFFICIENT_SPEED:"12",GALLONS_PER_HOUR:"4",GPH_AT_MAX_SPEED:"7",FUEL_CAPACITY:"60",ISDEFAULTVESSEL:1,MAKE:"Fixture",MODEL:"Canonical",COLOR:"White",HOMEPORT:""}}));
      result.push(await Api.saveContact({contact:{CONTACTID:0,CONTACTNAME:"Auth Live Shore",PHONE:"7275550123",EMAIL:email}}));
      result.push(await Api.saveOperator({operator:{OPERATORID:0,OPERATORNAME:"Separate Live Captain",PHONE:"",NOTES:""}}));
      result.push(await Api.saveWaypoint({waypoint:{WAYPOINTID:0,WAYPOINTNAME:"Auth Live Start",LATITUDE:"27.9506",LONGITUDE:"-82.4572",NOTES:""}}));
      await FPW.DashboardModules.onboarding.refresh();
      const partial=await Api.getDashboardOnboardingState();
      result.push({partial});
      result.push(await Api.saveWaypoint({waypoint:{WAYPOINTID:0,WAYPOINTNAME:"Auth Live End",LATITUDE:"27.9770",LONGITUDE:"-82.8270",NOTES:""}}));
      await FPW.DashboardModules.onboarding.refresh();
      return result;
    },{email});
    for(const result of results) if(!result.partial) expect(result.SUCCESS,JSON.stringify(result)).toBe(true);
    const partial=results.find(x=>x.partial).partial;
    expect((partial.ONBOARDING||partial.onboarding).checklist.allComplete).toBe(false);
    await expect(page.locator("#authContinuationBtn")).toBeEnabled();
    await expect(page.locator("#routeBuilderModal")).toBeHidden();
    await page.reload();
    await expect(page.locator("#authContinuationBtn")).toBeEnabled();
    await expect(page.locator("#authContinuationPanel")).toBeVisible();
    await expect(page.locator("#routeBuilderModal")).toBeHidden();
    expect(await page.locator("body").getAttribute("data-auth-wait-for-continue")).toBe("true");
    record("vessel/contact/operator/two-waypoint readiness enables explicit Continue; reload never auto-opens planner");
    await page.locator("#authContinuationBtn").click();
    await expect(page.locator("#routeBuilderModal")).toBeVisible({timeout:30000});
    await expect(page.locator("#authContinuationPanel")).toBeHidden();
    await expect(page).not.toHaveURL(/authIntent=/);
    record("explicit Continue opens requested planner and consumes only after tool opens");
    }
    const profile=await page.evaluate(()=>Api.getProfileName());
    expect(profile.PROFILE.hasName||profile.PROFILE.HASNAME||false).toBe(false);
    record("planning works without a member name");
    await page.goto(BASE+"/great-loop/trip-planning/");
    await page.locator('a[data-fpw-auth-intent="planner"][data-fpw-auth-section="daily_decisions"]').click();
    await expect(page.locator("#routeBuilderModal")).toBeVisible({timeout:30000});
    await expect(page.locator("#fpwAuthModal")).toBeHidden();
    record("existing eligible authenticated member bypasses modal and reaches planner");

    await page.evaluate(()=>Api.logout());
    await page.goto(BASE+"/great-loop/trip-planning/");
    await page.locator('a[data-fpw-auth-intent="planner"][data-fpw-auth-section="daily_decisions"]').click();
    await page.locator("#fpwAuthEmail").fill(email);
    await page.locator("#fpwAuthPassword").fill("incorrect");
    await page.locator("#fpwAuthContinue").click();
    await expect(page.locator("#fpwAuthAlert")).toContainText("Invalid email or password");
    await expect(page.locator("#fpwAuthEmail")).toHaveValue(email);
    await page.locator("#fpwAuthPassword").fill(password);
    await page.locator("#fpwAuthContinue").click();
    await expect(page.locator("#routeBuilderModal")).toBeVisible({timeout:30000});
    record("existing eligible member modal login; wrong password remains inline and preserves email/goal");

    const tokens=await page.evaluate(async()=>{
      return {account:await Api.authBootstrap({destinationKey:"account"}),planner:await Api.authBootstrap({destinationKey:"planner"})};
    });
    expect(tokens.account.INTENT_TOKEN).not.toBe(tokens.planner.INTENT_TOKEN);
    const other=await context.newPage();
    await other.goto(BASE+"/app/account.cfm?authIntent="+tokens.account.INTENT_TOKEN);
    await expect(other).not.toHaveURL(/authIntent=/);
    const pending=await page.evaluate(token=>Api.authBootstrap({intentToken:token}),tokens.planner.INTENT_TOKEN);
    expect(pending.AUTH).toBe(true);
    const stranger=await browser.newContext();const outsider=await stranger.request.get(BASE+"/api/v1/auth.cfc?method=bootstrap&intentToken="+tokens.planner.INTENT_TOKEN);
    expect(outsider.status()).toBe(400);
    await stranger.close();
    await page.evaluate(token=>Api.dismissAuthIntent(token),tokens.planner.INTENT_TOKEN);
    await other.close();
    record("two independent tab goals; Account acknowledgement preserves planner goal; foreign session cannot use token");

    await page.evaluate(()=>Api.logout());
    await page.setViewportSize({width:390,height:844});
    await page.goto(BASE+"/great-loop/trip-planning/");
    const menu=page.locator("[data-fpw-mobile-toggle]");
    await menu.click();
    await expect(menu).toHaveAttribute("aria-expanded","true");
    await page.locator('a[data-fpw-auth-intent="dashboard"][data-fpw-auth-source-page="top_nav"]').click();
    await expect(menu).toHaveAttribute("aria-expanded","false");
    await expect(page.locator("#fpwAuthModal")).toBeVisible();
    const bounds=await page.locator("#fpwAuthModal").boundingBox();
    expect(bounds.width).toBeLessThanOrEqual(390);
    await page.locator("#fpwAuthEmail").fill(email);await page.locator("#fpwAuthPassword").fill(password);
    await page.locator("#fpwAuthContinue").click();
    await page.waitForURL(/app\/dashboard\.cfm/);
    await expect(page.locator("[data-fpw-member-identity]").first()).toHaveText(email);
    record("mobile top-nav Login opens Dashboard without requesting planner prerequisites");
    expect(pageErrors).toEqual([]);
    record("no browser JavaScript exceptions");
    expect(authEvents.some(e=>e.name==="auth_continuation_success")).toBe(true);
    const telemetry=JSON.stringify(authEvents);
    expect(telemetry).not.toContain(email);
    expect(telemetry).not.toContain(password);
    if(ledger.intentToken) expect(telemetry).not.toContain(ledger.intentToken);
    expect(telemetry).not.toContain("http://");
    if(!resume) expect(authEvents.filter(e=>e.name==="auth_account_created")).toHaveLength(1);
    ledger.analyticsEvents=authEvents;
    record("funnel events exclude credentials, email, full URLs and intent tokens");
    ledger.success=true;
  } finally {
    fs.writeFileSync(artifact,JSON.stringify(ledger,null,2),{mode:0o600});
    await context.storageState({path:artifact.replace(".json","-session.json")});
    await context.close();
  }
});
