<!--- Generated by node scripts/generate-boat-cost-examples.cjs; do not hand-edit results. --->
<div class="bc-example-actions"><button type="button" class="bc-button" data-boat-cost-example="H">Try $25,000 trailer-kept powerboat</button><button type="button" class="bc-button" data-boat-cost-example="B">Try $50,000 slip-kept cruiser</button><button type="button" class="bc-button" data-boat-cost-example="I">Try $100,000 larger cruiser</button></div>
<p>All three are used powerboats, financed purchases, with illustrative assumptions. Physical length, engine count, model year, engine type, water, season and state are unspecified; they do not change these direct storage or total-vessel fuel calculations. Every included amount is illustrative; excluded categories are not assumed free.</p>
<div class="bc-table-scroll" tabindex="0" role="region" aria-label="Worked example assumptions and results"><table class="bc-table"><caption>Complete version 1.0 illustrative input packs and engine-generated results</caption><thead><tr><th scope="col">Assumption or result</th><th scope="col">$25,000 trailer-kept powerboat</th><th scope="col">$50,000 slip-kept cruiser</th><th scope="col">$100,000 larger cruiser</th></tr></thead><tbody>
<tr><th scope="row">Boat price</th><td>$25,000.00</td><td>$50,000.00</td><td>$100,000.00</td></tr>
<tr><th scope="row">Down payment in dollars</th><td>$5,000.00</td><td>$10,000.00</td><td>$20,000.00</td></tr>
<tr><th scope="row">Contract annual interest rate</th><td>8%</td><td>8%</td><td>8%</td></tr>
<tr><th scope="row">Loan term</th><td>120 months</td><td>120 months</td><td>180 months</td></tr>
<tr><th scope="row">Purchase tax (cash-paid dollar amount)</th><td>$1,500.00</td><td>$3,000.00</td><td>$6,000.00</td></tr>
<tr><th scope="row">Title/documentation fee (cash-paid)</th><td>$300.00</td><td>$500.00</td><td>$1,000.00</td></tr>
<tr><th scope="row">Dealer, lender and other purchase fees</th><td>Explicitly excluded</td><td>Explicitly excluded</td><td>Explicitly excluded</td></tr>
<tr><th scope="row">Annual boat running hours</th><td>80 hours</td><td>100 hours</td><td>100 hours</td></tr>
<tr><th scope="row">Total GPH for all propulsion engines</th><td>6 GPH</td><td>8 GPH</td><td>20 GPH</td></tr>
<tr><th scope="row">Fuel price per US gallon</th><td>$5.00</td><td>$5.00</td><td>$5.00</td></tr>
<tr><th scope="row">Generator</th><td>Explicitly excluded</td><td>Explicitly excluded</td><td>Explicitly excluded</td></tr>
<tr><th scope="row">Annual storage (direct annual amount)</th><td>$1,200.00</td><td>$3,000.00</td><td>$9,000.00</td></tr>
<tr><th scope="row">Annual insurance</th><td>$600.00</td><td>$1,000.00</td><td>$2,400.00</td></tr>
<tr><th scope="row">Annual routine maintenance</th><td>$900.00</td><td>$1,500.00</td><td>$4,000.00</td></tr>
<tr><th scope="row">Annual registration and recurring taxes</th><td>$150.00</td><td>$250.00</td><td>$400.00</td></tr>
<tr><th scope="row">Annual seasonal services</th><td>Excluded</td><td>$250.00</td><td>$1,200.00</td></tr>
<tr><th scope="row">Other operations, utilities, pump-outs, towing, trailer upkeep, launch fees and subscriptions</th><td>Explicitly excluded</td><td>Explicitly excluded</td><td>Explicitly excluded</td></tr>
<tr><th scope="row">Survey</th><td>$500.00</td><td>$600.00</td><td>$1,200.00</td></tr>
<tr><th scope="row">Inspection haul-out</th><td>Excluded</td><td>$300.00</td><td>$800.00</td></tr>
<tr><th scope="row">Engine inspection</th><td>Excluded</td><td>$300.00</td><td>$1,000.00</td></tr>
<tr><th scope="row">Immediate repairs</th><td>$500.00</td><td>Excluded</td><td>$2,000.00</td></tr>
<tr><th scope="row">Safety equipment</th><td>Excluded</td><td>$300.00</td><td>Excluded</td></tr>
<tr><th scope="row">Delivery, batteries, electronics, initial bottom work and trailer purchase</th><td>Explicitly excluded</td><td>Explicitly excluded</td><td>Explicitly excluded</td></tr>
<tr><th scope="row">Initial repair reserve</th><td>$2,000.00</td><td>$2,000.00</td><td>$5,000.00</td></tr>
<tr><th scope="row">Annual repair savings</th><td>$600.00</td><td>$1,200.00</td><td>$3,000.00</td></tr>
<tr><th scope="row">Resale and selling costs (both horizons)</th><td>Excluded; no resale assumed</td><td>Excluded; no resale assumed</td><td>Excluded; no resale assumed</td></tr>
<tr><th scope="row">Annual operating expenses</th><td data-example-output="H.annualOperations">$5,250.00</td><td data-example-output="B.annualOperations">$10,000.00</td><td data-example-output="I.annualOperations">$27,000.00</td></tr>
<tr><th scope="row">Other initial and first-year costs</th><td data-example-output="H.preparation">$1,000.00</td><td data-example-output="B.preparation">$1,500.00</td><td data-example-output="I.preparation">$5,000.00</td></tr>
<tr><th scope="row">Monthly loan payment</th><td data-example-output="H.monthlyPayment">$242.66</td><td data-example-output="B.monthlyPayment">$485.31</td><td data-example-output="I.monthlyPayment">$764.52</td></tr>
<tr><th scope="row">Estimated monthly boating budget</th><td data-example-output="H.monthlyBudget">$730.16</td><td data-example-output="B.monthlyBudget">$1,418.64</td><td data-example-output="I.monthlyBudget">$3,264.52</td></tr>
<tr><th scope="row">First-year funding target</th><td data-example-output="H.firstYearFunding">$18,561.86</td><td data-example-output="B.firstYearFunding">$34,023.72</td><td data-example-output="I.firstYearFunding">$76,174.26</td></tr>
</tbody></table></div>
